### ISSUE TITLE
Altitude estimation and saving in a file

### ISSUE THREAD

**Issue by donkarlo** [ctu-mrs/mrs_uav_odometry#7]
- Is there any estimation for altitude?
- How can I save odometry data of a drone following a trajectory in a file?

**Comment by petrlmat** [comment]
Hi, yes there is altitude estimation based on various sensors. You can check out the config file `config/altitude_estimator.yaml` for estimators and measurements that we use.
The easiest way to save odometry data in a file is to record a rosbag file with the drone following the trajectory and then load the rosbag in a python script and save the data to e.g. csv file. Or you can do it even from terminal `rostopic echo -b file.bag -p /topic > data.txt`

**Comment by donkarlo** [comment]
Thanks a lot. This is really helpful
